#index:
#    path: /
#    controller: App\Controller\DefaultController::index
authentication_token:
    path: /api/login_check
    methods: ['POST']
#creation users
create_user:
   path: /api/create/user
   controller: App\Controller\UserController::addUser
   methods: ['POST']
#creation partenaire 
create_partenaire:
   path: /api/partenaire/create
   controller: App\Controller\PartenaireController::addPartenaireEtCompte
   methods: ['POST']
#attribuer des utilisareurs a un compte donc a une agence 
attribuer_users_partenaire:
   path: /api/partenaire/{id}/ajout-users
   controller: App\Controller\PartenaireController::AttibuerUsersAgence
   methods: ['POST']
#edit users
edit_user:
   path: /api/users/{id}
   controller: App\Controller\UserController::EditUser
   methods: ['POST']
#edit partenaire
editer_partenaire:
   path: /api/update/partenaire/{id}
   controller: App\Controller\PartenaireController::EditPartenaire
   methods: ['POST']

#edit partenaire
bloquer_partenaire:
   path: /api/bloquer/partenaire/{id}
   controller: App\Controller\PartenaireController::BloquerPartenaire
   methods: ['DELETE']
#faire-depot
faire_depot:
   path: /api/faire/depot
   controller: App\Controller\PartenaireController::FaireDepot
   methods: ['POST']
# faire une transaction (depot)
faire_transaction_depot:
   path: /api/envoyer/argent
   controller: App\Controller\TransactionController::EnvoyerArgent
   methods: ['POST']
# faire un retrait 
faire_transaction_retrait:
   path: /api/retirer/argent
   controller: App\Controller\TransactionController::RetirerArgent
   methods: ['POST']

# Recuperer la transaction d un utilisateur 
recuperer_transaction_utilisateur:
   path: /api/user/{id}/transactions
   controller: App\Controller\TransactionController::AffciherTransactionUser
   methods: ['GET']

# Recuperer la transaction d une agence 
recuperer_transaction_agence:
   path: /api/agence/{id}/transactions
   controller: App\Controller\TransactionController::AfficherTransactionsAgence
   methods: ['GET']   

#delete user
delete_user:
   path: /api/supprimer/user/{id}
   controller: App\Controller\UserController::deleteUser
   methods: ['DELETE']
#Bloquer user
bloquer_user:
   path: /api/bloquer/user/{id}
   controller: App\Controller\UserController::BloquerUser
   methods: ['DELETE']
#annuler depot 
annuler_depot:
   path: /api/annuler/dernier/depot
   controller: App\Controller\PartenaireController::AnnulerDepot
   methods: ['DELETE']
#les transactions d un caissier 
liste_depots_caissier:
   path: /api/depots/{id}/caissier
   controller: App\Controller\PartenaireController::DepotOneUser
   methods: ['GET']
#annuler transaction 
annuler_transaction:
   path: /api/annuler/dernier/transaction
   controller: App\Controller\TransactionController::AnnulerTransaction
   methods: ['POST']

#Recuperer tatif 
recuperer_tarif:
   path: /api/Trouvertarif
   controller: App\Controller\TransactionController::TrouverTarif
   methods: ['POST']
#Recuperer code 
recuperer_code:
   path: /api/TrouverCode
   controller: App\Controller\TransactionController::TrouverCoder
   methods: ['POST']
